# Generated by Django 5.1.4 on 2026-06-21 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY_FOR_EDITING', 'Ready for editing'), ('EXPORTING', 'Exporting'), ('COMPLETED', 'Completed'), ('FAILED_UPLOAD', 'Failed upload'), ('FAILED_TRANSCRIPT', 'Failed transcript'), ('FAILED_EXPORT', 'Failed export')], default='DRAFT', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
