# Generated by Django 5.1.4 on 2026-06-22 14:32

import apps.subtitles.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset', models.CharField(default='reels', max_length=32)),
                ('file', models.FileField(blank=True, upload_to=apps.subtitles.models.subtitle_upload_path)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
