# Generated by Django 5.1.4 on 2026-06-22 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('silence', 'Silence'), ('breath', 'Breath')], max_length=16)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_operations', to='projects.project')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
