# Generated by Django 5.1.4 on 2026-06-21 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('hook', models.TextField(blank=True, default='')),
                ('script', models.TextField(blank=True, default='')),
                ('shot_list', models.JSONField(blank=True, default=list)),
                ('cta', models.TextField(blank=True, default='')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
